### ISSUE TITLE
A proper tool for maps will be found

### ISSUE THREAD

**Issue by Simurgan** [Simurgan/mappaturcorum#5]
The project will include a map that shows some data locations and a proper tool should be found for that purpose.

- The map should be showing altitudes and the geography (like mountains etc).
- The map should be zoomed in and out.
- The map should support features like popups on hover and on click on the data points.

**Comment by burakkizilay46** [comment]
https://leafletjs.com/

- i dont know have showing altidues, need research.
- we have zoom in and out in this package.
- i think is support but need research.

**Comment by Simurgan** [comment]
I have reviewed leaflet and I think it is amazing. It is exactly what we need and also there is [an npm package for react + leaflet](https://www.npmjs.com/package/react-leaflet?activeTab=readme). This will easen our job and also we will be able to draw lines that represent ordinary people's migrations and regions that represent old historical ares in the map. Thank you for your valuable research and I think we should go with leaflet in the project @burakkizilay46 .

Since the research is concluded, I am closing this issue.
P.S this is the first closed issue on the repository. Congrats @burakkizilay46

**Comment by burakkizilay46** [comment]
Thanks for comments 🚀🚀🚀🚀🚀
